/**
 * Pure helpers shared by the client, the API routes, and the tests for
 * per-user cloud recording storage (Vercel Blob + Clerk).
 *
 * Layout in the blob store:
 *
 *   recordings/{userId}/{recordingId}{randomSuffix}.{ext}   media (client upload)
 *   recordings/{userId}/{recordingId}.json                  metadata (server put)
 *
 * Every blob for a user lives under `recordings/{userId}/`, and every route
 * validates ownership with `assertOwnedRecordingPath` before doing anything.
 * This module must stay dependency-free so it can be unit-tested directly.
 */

export const RECORDINGS_ROOT = "recordings";

/** Content types the browser's MediaRecorder can produce for practice takes. */
export const ALLOWED_MEDIA_CONTENT_TYPES = [
  "video/webm",
  "video/mp4",
  "video/quicktime",
  "video/x-matroska",
  "audio/webm",
  "audio/mp4",
  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
  "audio/x-wav",
  "audio/ogg",
  "audio/aac",
] as const;

/** Hard cap for one uploaded practice recording. */
export const MAX_MEDIA_BYTES = 1024 * 1024 * 1024; // 1 GB

/** Client-side metadata for a recording stored in the cloud. */
export type CloudRecordingMetadata = {
  id: string;
  topicId: string;
  topicName: string;
  challengeQuestion?: string;
  categoryId: string;
  categoryName: string;
  difficulty: string;
  prepMinutes: number;
  notes?: string;
  durationSeconds: number;
  createdAt: string;
  transcript?: string;
  /** Server-side JSON blob (serde) — clients keep media out of metadata. */
  metrics?: unknown;
  evaluation?: unknown;
  storage: "cloud";
  /** Full public URL of the uploaded media blob. */
  mediaUrl: string;
  /** Path of the media blob inside the store, e.g. recordings/{userId}/{id}.webm */
  mediaPathname: string;
  mediaSize?: number;
  mediaContentType?: string;
};

/** Recording ids look like `1737420000000-8f31c0a9b2d4` — safe in a pathname. */
export function newRecordingId(): string {
  return `${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

/** Recording ids are generated by this app; anything else must be rejected. */
export function sanitizeRecordingId(id: string): string {
  if (!/^[A-Za-z0-9_-]{1,80}$/.test(id)) {
    throw new Error("Invalid recording id.");
  }
  return id;
}

/** Map a recorded blob's MIME type to a safe file extension. */
export function safeExtensionForContentType(contentType: string): string {
  const base = contentType.split(";")[0].trim().toLowerCase();
  switch (base) {
    case "video/webm":
    case "audio/webm":
      return "webm";
    case "video/mp4":
    case "audio/mp4":
    case "audio/aac":
      return "mp4";
    case "video/quicktime":
      return "mov";
    case "video/x-matroska":
      return "mkv";
    case "audio/mpeg":
    case "audio/mp3":
      return "mp3";
    case "audio/wav":
    case "audio/x-wav":
      return "wav";
    case "audio/ogg":
      return "ogg";
    default:
      return "webm";
  }
}

/** `recordings/{userId}/{recordingId}.json` — the per-recording metadata blob. */
export function metadataPathFor(userId: string, recordingId: string): string {
  const safeUserId = sanitizeRecordingId(userId);
  const safeId = sanitizeRecordingId(recordingId);
  return `${RECORDINGS_ROOT}/${safeUserId}/${safeId}.json`;
}

/** `recordings/{userId}/{recordingId}.{ext}` — base pathname for the media upload. */
export function mediaPathFor(userId: string, recordingId: string, extension: string): string {
  const safeUserId = sanitizeRecordingId(userId);
  const safeId = sanitizeRecordingId(recordingId);
  if (!/^[a-z0-9]{2,8}$/.test(extension)) {
    throw new Error("Invalid media extension.");
  }
  return `${RECORDINGS_ROOT}/${safeUserId}/${safeId}.${extension}`;
}

/** List prefix that scopes every recording of one user (metadata + media). */
export function recordingsPrefixFor(userId: string): string {
  const safeUserId = sanitizeRecordingId(userId);
  return `${RECORDINGS_ROOT}/${safeUserId}/`;
}

/**
 * Every blob touched on behalf of a user must live inside their own folder.
 * Throws unless `pathname` is `recordings/{userId}/…` with a safe remainder.
 * (The media path also carries a Vercel-generated random suffix — allow it.)
 */
export function assertOwnedRecordingPath(userId: string, pathname: string): void {
  const prefix = recordingsPrefixFor(userId);
  if (!pathname.startsWith(prefix)) {
    throw new Error("Recording paths must live inside the signed-in user's folder.");
  }
  const remainder = pathname.slice(prefix.length);
  if (!remainder || remainder.includes("..") || remainder.includes("/") || /[^A-Za-z0-9._-]/.test(remainder.replace(/\s/g, ""))) {
    throw new Error("Invalid recording path.");
  }
}

/**
 * Validate and normalize the metadata body sent by the client before it is
 * written to the store. Returns a clean CloudRecordingMetadata or throws.
 * The fields mirror SavedRecording (minus `blob`) plus the media pointers.
 */
export function parseRecordingMetadata(
  input: unknown,
  expected: { userId: string; recordingId: string },
): CloudRecordingMetadata {
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    throw new Error("Invalid recording metadata.");
  }
  const raw = input as Record<string, unknown>;

  if (raw.id !== expected.recordingId) {
    throw new Error("Recording metadata id does not match the target recording.");
  }

  const requireString = (value: unknown, field: string, max = 400): string => {
    if (typeof value !== "string" || !value.trim() || value.length > max) {
      throw new Error(`Invalid recording metadata field: ${field}.`);
    }
    return value;
  };
  const optionalString = (value: unknown, max: number): string | undefined => {
    if (value === undefined || value === null) return undefined;
    if (typeof value !== "string" || value.length > max) {
      throw new Error("Invalid recording metadata field.");
    }
    return value;
  };

  const mediaUrl = requireString(raw.mediaUrl, "mediaUrl", 2000);
  const mediaPathname = requireString(raw.mediaPathname, "mediaPathname", 300);
  // The client can only ever point the recording at media it uploaded into
  // its own folder. Enforce that here as well (server-side authority).
  if (mediaUrl.includes("<") || mediaUrl.includes(">") || !/^https:\/\//.test(mediaUrl)) {
    throw new Error("Invalid media URL.");
  }
  assertOwnedRecordingPath(expected.userId, mediaPathname);

  const duration = Number(raw.durationSeconds);
  if (!Number.isFinite(duration) || duration < 0 || duration > 24 * 60 * 60) {
    throw new Error("Invalid recording duration.");
  }
  const prepMinutes = Number(raw.prepMinutes);
  if (!Number.isFinite(prepMinutes) || prepMinutes < 0 || prepMinutes > 24 * 60) {
    throw new Error("Invalid prep duration.");
  }
  const createdAt = requireString(raw.createdAt, "createdAt", 40);
  if (Number.isNaN(new Date(createdAt).getTime())) {
    throw new Error("Invalid recording creation date.");
  }

  const metadata: CloudRecordingMetadata = {
    id: sanitizeRecordingId(expected.recordingId),
    topicId: requireString(raw.topicId, "topicId", 120),
    topicName: requireString(raw.topicName, "topicName", 300),
    categoryId: requireString(raw.categoryId, "categoryId", 120),
    categoryName: requireString(raw.categoryName, "categoryName", 200),
    difficulty: requireString(raw.difficulty, "difficulty", 40),
    prepMinutes,
    durationSeconds: Math.round(duration),
    createdAt,
    storage: "cloud",
    mediaUrl,
    mediaPathname,
  };

  const challengeQuestion = optionalString(raw.challengeQuestion, 600);
  if (challengeQuestion !== undefined) metadata.challengeQuestion = challengeQuestion;
  const notes = optionalString(raw.notes, 20000);
  if (notes !== undefined) metadata.notes = notes;
  const transcript = optionalString(raw.transcript, 500000);
  if (transcript !== undefined) metadata.transcript = transcript;
  if (raw.metrics !== undefined && raw.metrics !== null) {
    if (typeof raw.metrics !== "object" || Array.isArray(raw.metrics)) {
      throw new Error("Invalid recording metrics.");
    }
    metadata.metrics = raw.metrics;
  }
  if (raw.evaluation !== undefined && raw.evaluation !== null) {
    if (typeof raw.evaluation !== "object" || Array.isArray(raw.evaluation)) {
      throw new Error("Invalid recording evaluation.");
    }
    metadata.evaluation = raw.evaluation;
  }
  if (raw.mediaSize !== undefined && raw.mediaSize !== null) {
    const size = Number(raw.mediaSize);
    if (!Number.isFinite(size) || size < 0 || size > MAX_MEDIA_BYTES) {
      throw new Error("Invalid media size.");
    }
    metadata.mediaSize = Math.round(size);
  }
  const mediaContentType = optionalString(raw.mediaContentType, 120);
  if (mediaContentType !== undefined) metadata.mediaContentType = mediaContentType;

  return metadata;
}
